# k8s/service-demo.yaml

apiVersion: v1
kind: Service
metadata:
  name: netflix-movie-catalog-service
spec:
  selector:
    app: netflix-movie-catalog
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
