# k8s/deployment-demo.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-frontend-deployment
  labels:
    app: netflix-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix-frontend
  template:
    metadata:
        labels:
          app: netflix-frontend
    spec:
      containers:
      - name: netflix-frontend-container
        image: alonithuji/netflix-frontend:0.0.1
        env:
          - name: MOVIE_CATALOG_SERVICE
            value: http://netflix-movie-catalog-service:8080
          - name: REDIS_URL
            value: redis://redis-service:6379
